### ISSUE TITLE
Viewed maps linger after navigating to new decade

### ISSUE THREAD

**Issue by subsublibrary** [nypl-spacetime/group-maps#1] opened 2016-07-22 14:05 UTC
Sorry if this issue is in the wrong repo, didn't see one for Maps by Decade simple (sans 'data').

So, if I've opted to view a map sheet on the map and then navigate (via the prev/next buttons) to a different decade, the viewed map remains on screen.

**Comment by bertspaan** [comment] 2016-07-22 14:10
This is indeed wrong repo, `maps-by-decade` repo is private, I will add you as collaborator to org.

The fact that maps linger is by design.

**Comment by subsublibrary** [comment] 2016-07-22 14:19
I had zoomed far in on a map on the left, then advanced to a new decade. But the old map still filled the screen. I won't insist on changing, but it was confusing to me.

**Comment by bertspaan** [comment] 2016-07-22 14:29
I will make the map disappear when new decade is selected, you're right, is probably better.

**Comment by bertspaan** [comment] 2016-07-22 14:33
However, if we allow users to select multiple tile layers, we should reconsider this. Then we should probably always keep showing selected maps (with tiles on map) in the sidebar.

**Comment by bertspaan** [comment] 2016-07-22 14:35
Closed by 2c928c83acdd1cd8e8a5d14b23abd55430a7b27f

**Closed as completed** 2016-07-22 14:36 UTC
